# Generated by Django 3.0.5 on 2021-12-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20211210_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='date_added',
        ),
    ]
