# Generated by Django 3.0.5 on 2021-12-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0012_image_pizza'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='pizzas_image',
        ),
    ]
