# Generated by Django 3.0.5 on 2021-12-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0018_auto_20211212_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pizzas/media'),
        ),
    ]
