# Generated by Django 3.0.5 on 2021-12-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0019_auto_20211212_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza_Image',
        ),
    ]
