# Generated by Django 3.0.5 on 2021-12-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0020_delete_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pizzas/static/pizzas/media'),
        ),
    ]
