# Generated by Django 3.0.5 on 2021-12-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0025_auto_20211212_0306'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
