# Generated by Django 3.0.5 on 2021-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0026_auto_20211212_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pic',
            field=models.ImageField(default=1, upload_to='./static/pizzas/media'),
            preserve_default=False,
        ),
    ]
