# Generated by Django 3.0.5 on 2021-12-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0027_pizza_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pic',
        ),
    ]
